#!/usr/bin/env python3
from sys import argv

def factorize(number):
    """Return a pair of factors of the given number.
    """
    for factor in range(2, int(number ** (0.5))+1):
        if number % factor == 0:
            return number // factor, factor

def main():
    """Read numbers from a file and print their factorization.
    """
    if len(argv) != 2:
        print("Usage factors <file>")
        return 1
    filename = argv[1]
    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            factor_pairs = factorize(number)
            #print("{}={}*{}".format(number, factor_pairs[0], factor_pairs[1]))
            print(f"{number}={factor_pairs[0]}*{factor_pairs[1]}")

if __name__ == "__main__":
    main()
    
