#!/usr/bin/env python3
from sys import argv

def is_prime(number):
    if number <= 1:
        return False
    for factor in range (2, int(number ** 0.5)+1):
        if number % factor == 0:
            return False
    return True

def factorize(number):
    """
    """
    for factor in range(2, int(number ** 0.5) + 1):
        if number % factor == 0:
            other_factor = number // factor
            if is_prime(factor) and is_prime(other_factor):
                return other_factor, factor
    return None

def main():
    """
    """
    if len(argv) != 2:
        print("Usage: rsa <file>")
        return 1

    filename = argv[1]
    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            factors_pairs = factorize(number)
            if factors_pairs == None:
                print(f"{number} is not a semi-prime number")
            else:
                print(f"{number}={factors_pairs[0]}*{factors_pairs[1]}")
if __name__ == "__main__":
    main()

