#!/usr/bin/env python3

import sys
from math import isqrt

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, isqrt(num) + 1):
        if num % i == 0:
            return False
    return True

def find_prime_factors(number):
    for i in range(2, isqrt(number) + 1):
        if number % i == 0 and is_prime(i) and is_prime(number // i):
            return i, number // i
    return None, None

def main():
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    input_file = sys.argv[1]

    with open(input_file, 'r') as file:
        for line in file:
            number = int(line.strip())
            factor1, factor2 = find_prime_factors(number)
            if factor1 and factor2:
                print("{}={}*{}".format(number, factor1, factor2))

if __name__ == "__main__":
    main()
